=begin
#Accounts API

#Accounts API 

OpenAPI spec version: 0.9.5

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.27
=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::PartitionListAttributes
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'PartitionListAttributes' do
  before do
    # run before each test
    @instance = SwaggerClient::PartitionListAttributes.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PartitionListAttributes' do
    it 'should create an instance of PartitionListAttributes' do
      expect(@instance).to be_instance_of(SwaggerClient::PartitionListAttributes)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
