/*
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * MachineUserState
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-01T06:22:45.936666Z[Etc/UTC]")
public class MachineUserState {
  @SerializedName("current")
  private String current = null;

  @SerializedName("since")
  private String since = null;

  @SerializedName("actionBy")
  private String actionBy = null;

  public MachineUserState current(String current) {
    this.current = current;
    return this;
  }

   /**
   * Status of Machine User
   * @return current
  **/
  @Schema(example = "Active", required = true, description = "Status of Machine User")
  public String getCurrent() {
    return current;
  }

  public void setCurrent(String current) {
    this.current = current;
  }

  public MachineUserState since(String since) {
    this.since = since;
    return this;
  }

   /**
   * Status since time
   * @return since
  **/
  @Schema(example = "2021-11-06T00:00:00Z", required = true, description = "Status since time")
  public String getSince() {
    return since;
  }

  public void setSince(String since) {
    this.since = since;
  }

  public MachineUserState actionBy(String actionBy) {
    this.actionBy = actionBy;
    return this;
  }

   /**
   * was set to this status by(ID)
   * @return actionBy
  **/
  @Schema(example = "8e9833b5-b844-40a3-8572-4a16d29c53bc", required = true, description = "was set to this status by(ID)")
  public String getActionBy() {
    return actionBy;
  }

  public void setActionBy(String actionBy) {
    this.actionBy = actionBy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MachineUserState machineUserState = (MachineUserState) o;
    return Objects.equals(this.current, machineUserState.current) &&
        Objects.equals(this.since, machineUserState.since) &&
        Objects.equals(this.actionBy, machineUserState.actionBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(current, since, actionBy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MachineUserState {\n");
    
    sb.append("    current: ").append(toIndentedString(current)).append("\n");
    sb.append("    since: ").append(toIndentedString(since)).append("\n");
    sb.append("    actionBy: ").append(toIndentedString(actionBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
