/*
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UserRelationships;
import io.swagger.client.model.UserResponseAttributes;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * User
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-12-01T06:25:18.059872Z[Etc/UTC]")
public class User {
  @SerializedName("type")
  private String type = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("attributes")
  private UserResponseAttributes attributes = null;

  @SerializedName("relationships")
  private UserRelationships relationships = null;

  public User type(String type) {
    this.type = type;
    return this;
  }

   /**
   * type of the resource
   * @return type
  **/
  @Schema(example = "User", required = true, description = "type of the resource")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public User id(String id) {
    this.id = id;
    return this;
  }

   /**
   * ID of the user 
   * @return id
  **/
  @Schema(example = "8e9833b5-b844-40a3-8572-4a16d29c53bc", required = true, description = "ID of the user ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public User attributes(UserResponseAttributes attributes) {
    this.attributes = attributes;
    return this;
  }

   /**
   * Get attributes
   * @return attributes
  **/
  @Schema(description = "")
  public UserResponseAttributes getAttributes() {
    return attributes;
  }

  public void setAttributes(UserResponseAttributes attributes) {
    this.attributes = attributes;
  }

  public User relationships(UserRelationships relationships) {
    this.relationships = relationships;
    return this;
  }

   /**
   * Get relationships
   * @return relationships
  **/
  @Schema(description = "")
  public UserRelationships getRelationships() {
    return relationships;
  }

  public void setRelationships(UserRelationships relationships) {
    this.relationships = relationships;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return Objects.equals(this.type, user.type) &&
        Objects.equals(this.id, user.id) &&
        Objects.equals(this.attributes, user.attributes) &&
        Objects.equals(this.relationships, user.relationships);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, id, attributes, relationships);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    relationships: ").append(toIndentedString(relationships)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
