/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.CustomerAttributes
import io.swagger.server.models.CustomerMeta

/**
 *  * @param type  * @param id  * @param attributes  * @param meta */
data class Customer (        val type: Customer.Type,        val id: kotlin.String,        val attributes: CustomerAttributes,    val meta: CustomerMeta? = null
) {
    /**
    * 
    * Values: CUSTOMER
    */
    enum class Type(val value: kotlin.String){
        CUSTOMER("Customer");
    }
}
