/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.MachineUserOAuth
import io.swagger.server.models.MachineUserState

/**
 *  * @param name Name of Machine User * @param purpose Purpose of this machine user * @param state  * @param oAuth */
data class MachineUserResponseAttributes (        /* Name of Machine User */
        val name: kotlin.String,        /* Purpose of this machine user */
        val purpose: kotlin.String,        val state: MachineUserState,        val oAuth: MachineUserOAuth
) {
}
