/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 *  * @param createdAt  * @param updatedAt  * @param createdBy  * @param updatedBy */
data class MachineUserMeta (        val createdAt: java.time.LocalDateTime,    val updatedAt: java.time.LocalDateTime? = null,    val createdBy: kotlin.String? = null,    val updatedBy: kotlin.String? = null
) {
}
