/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models


/**
 * user identity details * @param emailId email address of the user * @param externalId horizon ID of the user within Siemens ID * @param familyName user's family name * @param fullName user's full name * @param givenName user's given name*/
data class UserResponseAttributesIdentity (        /* email address of the user */
        val emailId: kotlin.String,        /* horizon ID of the user within Siemens ID */
        val externalId: kotlin.String,        /* user's given name */
        val givenName: kotlin.String,    /* user's family name */    val familyName: kotlin.String? = null,    /* user's full name */    val fullName: kotlin.String? = null
) {
}
