/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server.models

import io.swagger.server.models.UserRelationships
import io.swagger.server.models.UserResponseAttributes

/**
 *  * @param type type of the resource * @param id ID of the user  * @param attributes  * @param relationships */
data class User (        /* type of the resource */
        val type: kotlin.String,        /* ID of the user  */
        val id: kotlin.String,    val attributes: UserResponseAttributes? = null,    val relationships: UserRelationships? = null
) {
}
