/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.ErrorErrors

/**
 * [More error information](docs/api-errors.html) 
 * @param errors 
 */
data class Error (

    val errors: kotlin.Array<ErrorErrors>
) {
}