/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param id A unique identifier for this particular occurrence of the problem.
 * @param code An application-specific error code, expressed as a string value.
 * @param status The HTTP status code applicable to this problem, expressed as a string value.
 * @param title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
 * @param detail a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.
 */
data class ErrorErrors (

    /* A unique identifier for this particular occurrence of the problem. */
    val id: kotlin.String,
    /* An application-specific error code, expressed as a string value. */
    val code: kotlin.String? = null,
    /* The HTTP status code applicable to this problem, expressed as a string value. */
    val status: kotlin.String,
    /* A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization. */
    val title: kotlin.String,
    /* a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized. */
    val detail: kotlin.String? = null
) {
}