/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.CustomerRelationship
import io.swagger.client.models.PartitionRelationship
import io.swagger.client.models.RoleRelationship

/**
 * 
 * @param hasAccessTo 
 * @param authorizedAs 
 * @param ownedBy 
 */
data class UserGroupRelationships (

    val hasAccessTo: PartitionRelationship? = null,
    val authorizedAs: RoleRelationship? = null,
    val ownedBy: CustomerRelationship? = null
) {
}