/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * additional details user by certain products
 * @param state State of the membership
 */
data class UserMembershipAttributes (

    /* State of the membership */
    val state: UserMembershipAttributes.State
) {
    /**
    * State of the membership
    * Values: ACTIVE,SUSPENDED
    */
    enum class State(val value: kotlin.String){
        ACTIVE("active"),
        SUSPENDED("suspended");
    }
}