/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserGroupRelationships
import io.swagger.client.models.UserGroupResponseAttribute

/**
 * 
 * @param type 
 * @param id 
 * @param attributes 
 * @param relationships 
 */
data class UserGroupResponseData (

    val type: kotlin.String,
    val id: kotlin.String,
    val attributes: UserGroupResponseAttribute,
    val relationships: UserGroupRelationships? = null
) {
}