/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import io.swagger.client.models.UserGroup
import io.swagger.client.models.UserGroupListLinks

/**
 * 
 * @param links 
 * @param &#x60;data&#x60; 
 */
data class UserGroupList (

    val links: UserGroupListLinks,
    val `data`: kotlin.Array<UserGroup>
) {
}