/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoleList struct {
	Links *RoleListLinks `json:"links"`
	Data []Role `json:"data"`
}
