/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorErrors struct {
	// A unique identifier for this particular occurrence of the problem.
	Id string `json:"id"`
	// An application-specific error code, expressed as a string value.
	Code string `json:"code,omitempty"`
	// The HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status"`
	// A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title string `json:"title"`
	// a human-readable explanation specific to this occurrence of the problem. Like title, this field’s value can be localized.
	Detail string `json:"detail,omitempty"`
}
