/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PagedUserGroupListResponseLinks struct {
	Self string `json:"self,omitempty"`
	Next string `json:"next,omitempty"`
}
