/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	// type of the resource
	Type_ string `json:"type"`
	// ID of the user 
	Id string `json:"id"`
	Attributes *UserResponseAttributes `json:"attributes,omitempty"`
	Relationships *UserRelationships `json:"relationships,omitempty"`
}
