/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MachineUser struct {
	Type_ string `json:"type"`
	// ID of the Machine User 
	Id string `json:"id"`
	Attributes *MachineUserResponseAttributes `json:"attributes,omitempty"`
	Relationships *MachineUserRelationships `json:"relationships,omitempty"`
	Meta *MachineUserMeta `json:"meta,omitempty"`
}
