/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PartitionList struct {
	Links *PartitionListLinks `json:"links"`
	Data []Partition `json:"data"`
	// Included resources based in `include` query param
	Included []PartitionListIncluded `json:"included,omitempty"`
}
