/*
 * Accounts API
 *
 * Accounts API 
 *
 * API version: 0.9.5
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RoleAttributes struct {
	TechnicalName string `json:"technicalName"`
	DisplayName string `json:"displayName"`
	Permissions []string `json:"permissions"`
}
