/* 
 * Accounts API
 *
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// UserGroupAttributes
    /// </summary>
    [DataContract]
        public partial class UserGroupAttributes :  IEquatable<UserGroupAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserGroupAttributes" /> class.
        /// </summary>
        /// <param name="name">Name of the user group  (required).</param>
        /// <param name="description">Description of the user group  (required).</param>
        /// <param name="isMachineEnabled">isMachineEnabled.</param>
        /// <param name="isSystemDefined">isSystemDefined.</param>
        public UserGroupAttributes(string name = default(string), string description = default(string), bool? isMachineEnabled = default(bool?), bool? isSystemDefined = default(bool?))
        {
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for UserGroupAttributes and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "description" is required (not null)
            if (description == null)
            {
                throw new InvalidDataException("description is a required property for UserGroupAttributes and cannot be null");
            }
            else
            {
                this.Description = description;
            }
            this.IsMachineEnabled = isMachineEnabled;
            this.IsSystemDefined = isSystemDefined;
        }
        
        /// <summary>
        /// Name of the user group 
        /// </summary>
        /// <value>Name of the user group </value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the user group 
        /// </summary>
        /// <value>Description of the user group </value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets IsMachineEnabled
        /// </summary>
        [DataMember(Name="isMachineEnabled", EmitDefaultValue=false)]
        public bool? IsMachineEnabled { get; set; }

        /// <summary>
        /// Gets or Sets IsSystemDefined
        /// </summary>
        [DataMember(Name="isSystemDefined", EmitDefaultValue=false)]
        public bool? IsSystemDefined { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserGroupAttributes {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IsMachineEnabled: ").Append(IsMachineEnabled).Append("\n");
            sb.Append("  IsSystemDefined: ").Append(IsSystemDefined).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserGroupAttributes);
        }

        /// <summary>
        /// Returns true if UserGroupAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of UserGroupAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserGroupAttributes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.IsMachineEnabled == input.IsMachineEnabled ||
                    (this.IsMachineEnabled != null &&
                    this.IsMachineEnabled.Equals(input.IsMachineEnabled))
                ) && 
                (
                    this.IsSystemDefined == input.IsSystemDefined ||
                    (this.IsSystemDefined != null &&
                    this.IsSystemDefined.Equals(input.IsSystemDefined))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                if (this.IsMachineEnabled != null)
                    hashCode = hashCode * 59 + this.IsMachineEnabled.GetHashCode();
                if (this.IsSystemDefined != null)
                    hashCode = hashCode * 59 + this.IsSystemDefined.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
