/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CustomerAttributes } from './customerAttributes';
import { CustomerMeta } from './customerMeta';

export interface Customer { 
    type: Customer.TypeEnum;
    id: string;
    attributes: CustomerAttributes;
    meta?: CustomerMeta;
}
export namespace Customer {
    export type TypeEnum = 'Customer';
    export const TypeEnum = {
        Customer: 'Customer' as TypeEnum
    };
}