/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserRelationships } from './userRelationships';
import { UserResponseAttributes } from './userResponseAttributes';

export interface User { 
    /**
     * type of the resource
     */
    type: string;
    /**
     * ID of the user 
     */
    id: string;
    attributes?: UserResponseAttributes;
    relationships?: UserRelationships;
}