/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * user identity details
 */
export interface UserResponseAttributesIdentity { 
    /**
     * email address of the user
     */
    emailId: string;
    /**
     * horizon ID of the user within Siemens ID
     */
    externalId: string;
    /**
     * user's family name
     */
    familyName?: string;
    /**
     * user's full name
     */
    fullName?: string;
    /**
     * user's given name
     */
    givenName: string;
}