# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.customer_info_api import CustomerInfoApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomerInfoApi(unittest.TestCase):
    """CustomerInfoApi unit test stubs"""

    def setUp(self):
        self.api = CustomerInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_partitions(self):
        """Test case for get_partitions

        List Partitions for Customer  # noqa: E501
        """
        pass

    def test_get_roles(self):
        """Test case for get_roles

        List Roles for Customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
