# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.user_group_response_attribute import UserGroupResponseAttribute  # noqa: E501
from swagger_client.rest import ApiException


class TestUserGroupResponseAttribute(unittest.TestCase):
    """UserGroupResponseAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserGroupResponseAttribute(self):
        """Test UserGroupResponseAttribute"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.user_group_response_attribute.UserGroupResponseAttribute()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
