# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.partition_list import PartitionList  # noqa: E501
from swagger_client.rest import ApiException


class TestPartitionList(unittest.TestCase):
    """PartitionList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartitionList(self):
        """Test PartitionList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.partition_list.PartitionList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
