# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.partition_relationship import PartitionRelationship  # noqa: E501
from swagger_client.rest import ApiException


class TestPartitionRelationship(unittest.TestCase):
    """PartitionRelationship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPartitionRelationship(self):
        """Test PartitionRelationship"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.partition_relationship.PartitionRelationship()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
