# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.me_api import MeApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMeApi(unittest.TestCase):
    """MeApi unit test stubs"""

    def setUp(self):
        self.api = MeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_me_usergroups(self):
        """Test case for get_me_usergroups

        Get the usergroups of caller  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
