# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CustomerAttributes Class
#'
#' @field name 
#' @field customerMembershipState 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomerAttributes <- R6::R6Class(
  'CustomerAttributes',
  public = list(
    `name` = NULL,
    `customerMembershipState` = NULL,
    initialize = function(`name`, `customerMembershipState`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`customerMembershipState`)) {
        stopifnot(R6::is.R6(`customerMembershipState`))
        self$`customerMembershipState` <- `customerMembershipState`
      }
    },
    toJSON = function() {
      CustomerAttributesObject <- list()
      if (!is.null(self$`name`)) {
        CustomerAttributesObject[['name']] <- self$`name`
      }
      if (!is.null(self$`customerMembershipState`)) {
        CustomerAttributesObject[['customerMembershipState']] <- self$`customerMembershipState`$toJSON()
      }

      CustomerAttributesObject
    },
    fromJSON = function(CustomerAttributesJson) {
      CustomerAttributesObject <- jsonlite::fromJSON(CustomerAttributesJson)
      if (!is.null(CustomerAttributesObject$`name`)) {
        self$`name` <- CustomerAttributesObject$`name`
      }
      if (!is.null(CustomerAttributesObject$`customerMembershipState`)) {
        customerMembershipStateObject <- UserMembershipAttributes$new()
        customerMembershipStateObject$fromJSON(jsonlite::toJSON(CustomerAttributesObject$customerMembershipState, auto_unbox = TRUE))
        self$`customerMembershipState` <- customerMembershipStateObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "customerMembershipState": %s
        }',
        self$`name`,
        self$`customerMembershipState`$toJSON()
      )
    },
    fromJSONString = function(CustomerAttributesJson) {
      CustomerAttributesObject <- jsonlite::fromJSON(CustomerAttributesJson)
      self$`name` <- CustomerAttributesObject$`name`
      UserMembershipAttributesObject <- UserMembershipAttributes$new()
      self$`customerMembershipState` <- UserMembershipAttributesObject$fromJSON(jsonlite::toJSON(CustomerAttributesObject$customerMembershipState, auto_unbox = TRUE))
    }
  )
)
