# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' CustomerRelationshipData Class
#'
#' @field type 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CustomerRelationshipData <- R6::R6Class(
  'CustomerRelationshipData',
  public = list(
    `type` = NULL,
    `id` = NULL,
    initialize = function(`type`, `id`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      CustomerRelationshipDataObject <- list()
      if (!is.null(self$`type`)) {
        CustomerRelationshipDataObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        CustomerRelationshipDataObject[['id']] <- self$`id`
      }

      CustomerRelationshipDataObject
    },
    fromJSON = function(CustomerRelationshipDataJson) {
      CustomerRelationshipDataObject <- jsonlite::fromJSON(CustomerRelationshipDataJson)
      if (!is.null(CustomerRelationshipDataObject$`type`)) {
        self$`type` <- CustomerRelationshipDataObject$`type`
      }
      if (!is.null(CustomerRelationshipDataObject$`id`)) {
        self$`id` <- CustomerRelationshipDataObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s
        }',
        self$`type`,
        self$`id`
      )
    },
    fromJSONString = function(CustomerRelationshipDataJson) {
      CustomerRelationshipDataObject <- jsonlite::fromJSON(CustomerRelationshipDataJson)
      self$`type` <- CustomerRelationshipDataObject$`type`
      self$`id` <- CustomerRelationshipDataObject$`id`
    }
  )
)
