# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' ErrorErrors Class
#'
#' @field id 
#' @field code 
#' @field status 
#' @field title 
#' @field detail 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ErrorErrors <- R6::R6Class(
  'ErrorErrors',
  public = list(
    `id` = NULL,
    `code` = NULL,
    `status` = NULL,
    `title` = NULL,
    `detail` = NULL,
    initialize = function(`id`, `code`, `status`, `title`, `detail`){
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`title`)) {
        stopifnot(is.character(`title`), length(`title`) == 1)
        self$`title` <- `title`
      }
      if (!missing(`detail`)) {
        stopifnot(is.character(`detail`), length(`detail`) == 1)
        self$`detail` <- `detail`
      }
    },
    toJSON = function() {
      ErrorErrorsObject <- list()
      if (!is.null(self$`id`)) {
        ErrorErrorsObject[['id']] <- self$`id`
      }
      if (!is.null(self$`code`)) {
        ErrorErrorsObject[['code']] <- self$`code`
      }
      if (!is.null(self$`status`)) {
        ErrorErrorsObject[['status']] <- self$`status`
      }
      if (!is.null(self$`title`)) {
        ErrorErrorsObject[['title']] <- self$`title`
      }
      if (!is.null(self$`detail`)) {
        ErrorErrorsObject[['detail']] <- self$`detail`
      }

      ErrorErrorsObject
    },
    fromJSON = function(ErrorErrorsJson) {
      ErrorErrorsObject <- jsonlite::fromJSON(ErrorErrorsJson)
      if (!is.null(ErrorErrorsObject$`id`)) {
        self$`id` <- ErrorErrorsObject$`id`
      }
      if (!is.null(ErrorErrorsObject$`code`)) {
        self$`code` <- ErrorErrorsObject$`code`
      }
      if (!is.null(ErrorErrorsObject$`status`)) {
        self$`status` <- ErrorErrorsObject$`status`
      }
      if (!is.null(ErrorErrorsObject$`title`)) {
        self$`title` <- ErrorErrorsObject$`title`
      }
      if (!is.null(ErrorErrorsObject$`detail`)) {
        self$`detail` <- ErrorErrorsObject$`detail`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "id": %s,
           "code": %s,
           "status": %s,
           "title": %s,
           "detail": %s
        }',
        self$`id`,
        self$`code`,
        self$`status`,
        self$`title`,
        self$`detail`
      )
    },
    fromJSONString = function(ErrorErrorsJson) {
      ErrorErrorsObject <- jsonlite::fromJSON(ErrorErrorsJson)
      self$`id` <- ErrorErrorsObject$`id`
      self$`code` <- ErrorErrorsObject$`code`
      self$`status` <- ErrorErrorsObject$`status`
      self$`title` <- ErrorErrorsObject$`title`
      self$`detail` <- ErrorErrorsObject$`detail`
    }
  )
)
