# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' MachineUserState Class
#'
#' @field current 
#' @field since 
#' @field actionBy 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MachineUserState <- R6::R6Class(
  'MachineUserState',
  public = list(
    `current` = NULL,
    `since` = NULL,
    `actionBy` = NULL,
    initialize = function(`current`, `since`, `actionBy`){
      if (!missing(`current`)) {
        stopifnot(is.character(`current`), length(`current`) == 1)
        self$`current` <- `current`
      }
      if (!missing(`since`)) {
        stopifnot(is.character(`since`), length(`since`) == 1)
        self$`since` <- `since`
      }
      if (!missing(`actionBy`)) {
        stopifnot(is.character(`actionBy`), length(`actionBy`) == 1)
        self$`actionBy` <- `actionBy`
      }
    },
    toJSON = function() {
      MachineUserStateObject <- list()
      if (!is.null(self$`current`)) {
        MachineUserStateObject[['current']] <- self$`current`
      }
      if (!is.null(self$`since`)) {
        MachineUserStateObject[['since']] <- self$`since`
      }
      if (!is.null(self$`actionBy`)) {
        MachineUserStateObject[['actionBy']] <- self$`actionBy`
      }

      MachineUserStateObject
    },
    fromJSON = function(MachineUserStateJson) {
      MachineUserStateObject <- jsonlite::fromJSON(MachineUserStateJson)
      if (!is.null(MachineUserStateObject$`current`)) {
        self$`current` <- MachineUserStateObject$`current`
      }
      if (!is.null(MachineUserStateObject$`since`)) {
        self$`since` <- MachineUserStateObject$`since`
      }
      if (!is.null(MachineUserStateObject$`actionBy`)) {
        self$`actionBy` <- MachineUserStateObject$`actionBy`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "current": %s,
           "since": %s,
           "actionBy": %s
        }',
        self$`current`,
        self$`since`,
        self$`actionBy`
      )
    },
    fromJSONString = function(MachineUserStateJson) {
      MachineUserStateObject <- jsonlite::fromJSON(MachineUserStateJson)
      self$`current` <- MachineUserStateObject$`current`
      self$`since` <- MachineUserStateObject$`since`
      self$`actionBy` <- MachineUserStateObject$`actionBy`
    }
  )
)
