# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PagedUserGroupListResponseLinks Class
#'
#' @field self 
#' @field next 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PagedUserGroupListResponseLinks <- R6::R6Class(
  'PagedUserGroupListResponseLinks',
  public = list(
    `self` = NULL,
    `next` = NULL,
    initialize = function(`self`, `next`){
      if (!missing(`self`)) {
        stopifnot(is.character(`self`), length(`self`) == 1)
        self$`self` <- `self`
      }
      if (!missing(`next`)) {
        stopifnot(is.character(`next`), length(`next`) == 1)
        self$`next` <- `next`
      }
    },
    toJSON = function() {
      PagedUserGroupListResponseLinksObject <- list()
      if (!is.null(self$`self`)) {
        PagedUserGroupListResponseLinksObject[['self']] <- self$`self`
      }
      if (!is.null(self$`next`)) {
        PagedUserGroupListResponseLinksObject[['next']] <- self$`next`
      }

      PagedUserGroupListResponseLinksObject
    },
    fromJSON = function(PagedUserGroupListResponseLinksJson) {
      PagedUserGroupListResponseLinksObject <- jsonlite::fromJSON(PagedUserGroupListResponseLinksJson)
      if (!is.null(PagedUserGroupListResponseLinksObject$`self`)) {
        self$`self` <- PagedUserGroupListResponseLinksObject$`self`
      }
      if (!is.null(PagedUserGroupListResponseLinksObject$`next`)) {
        self$`next` <- PagedUserGroupListResponseLinksObject$`next`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "self": %s,
           "next": %s
        }',
        self$`self`,
        self$`next`
      )
    },
    fromJSONString = function(PagedUserGroupListResponseLinksJson) {
      PagedUserGroupListResponseLinksObject <- jsonlite::fromJSON(PagedUserGroupListResponseLinksJson)
      self$`self` <- PagedUserGroupListResponseLinksObject$`self`
      self$`next` <- PagedUserGroupListResponseLinksObject$`next`
    }
  )
)
