# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' Partition Class
#'
#' @field type 
#' @field id 
#' @field attributes 
#' @field relationships 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Partition <- R6::R6Class(
  'Partition',
  public = list(
    `type` = NULL,
    `id` = NULL,
    `attributes` = NULL,
    `relationships` = NULL,
    initialize = function(`type`, `id`, `attributes`, `relationships`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`attributes`)) {
        stopifnot(R6::is.R6(`attributes`))
        self$`attributes` <- `attributes`
      }
      if (!missing(`relationships`)) {
        stopifnot(R6::is.R6(`relationships`))
        self$`relationships` <- `relationships`
      }
    },
    toJSON = function() {
      PartitionObject <- list()
      if (!is.null(self$`type`)) {
        PartitionObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        PartitionObject[['id']] <- self$`id`
      }
      if (!is.null(self$`attributes`)) {
        PartitionObject[['attributes']] <- self$`attributes`$toJSON()
      }
      if (!is.null(self$`relationships`)) {
        PartitionObject[['relationships']] <- self$`relationships`$toJSON()
      }

      PartitionObject
    },
    fromJSON = function(PartitionJson) {
      PartitionObject <- jsonlite::fromJSON(PartitionJson)
      if (!is.null(PartitionObject$`type`)) {
        self$`type` <- PartitionObject$`type`
      }
      if (!is.null(PartitionObject$`id`)) {
        self$`id` <- PartitionObject$`id`
      }
      if (!is.null(PartitionObject$`attributes`)) {
        attributesObject <- PartitionAttributes$new()
        attributesObject$fromJSON(jsonlite::toJSON(PartitionObject$attributes, auto_unbox = TRUE))
        self$`attributes` <- attributesObject
      }
      if (!is.null(PartitionObject$`relationships`)) {
        relationshipsObject <- PartitionRelationships$new()
        relationshipsObject$fromJSON(jsonlite::toJSON(PartitionObject$relationships, auto_unbox = TRUE))
        self$`relationships` <- relationshipsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s,
           "attributes": %s,
           "relationships": %s
        }',
        self$`type`,
        self$`id`,
        self$`attributes`$toJSON(),
        self$`relationships`$toJSON()
      )
    },
    fromJSONString = function(PartitionJson) {
      PartitionObject <- jsonlite::fromJSON(PartitionJson)
      self$`type` <- PartitionObject$`type`
      self$`id` <- PartitionObject$`id`
      PartitionAttributesObject <- PartitionAttributes$new()
      self$`attributes` <- PartitionAttributesObject$fromJSON(jsonlite::toJSON(PartitionObject$attributes, auto_unbox = TRUE))
      PartitionRelationshipsObject <- PartitionRelationships$new()
      self$`relationships` <- PartitionRelationshipsObject$fromJSON(jsonlite::toJSON(PartitionObject$relationships, auto_unbox = TRUE))
    }
  )
)
