# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' PartitionRelationshipData Class
#'
#' @field type 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
PartitionRelationshipData <- R6::R6Class(
  'PartitionRelationshipData',
  public = list(
    `type` = NULL,
    `id` = NULL,
    initialize = function(`type`, `id`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      PartitionRelationshipDataObject <- list()
      if (!is.null(self$`type`)) {
        PartitionRelationshipDataObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        PartitionRelationshipDataObject[['id']] <- self$`id`
      }

      PartitionRelationshipDataObject
    },
    fromJSON = function(PartitionRelationshipDataJson) {
      PartitionRelationshipDataObject <- jsonlite::fromJSON(PartitionRelationshipDataJson)
      if (!is.null(PartitionRelationshipDataObject$`type`)) {
        self$`type` <- PartitionRelationshipDataObject$`type`
      }
      if (!is.null(PartitionRelationshipDataObject$`id`)) {
        self$`id` <- PartitionRelationshipDataObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s
        }',
        self$`type`,
        self$`id`
      )
    },
    fromJSONString = function(PartitionRelationshipDataJson) {
      PartitionRelationshipDataObject <- jsonlite::fromJSON(PartitionRelationshipDataJson)
      self$`type` <- PartitionRelationshipDataObject$`type`
      self$`id` <- PartitionRelationshipDataObject$`id`
    }
  )
)
