# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' RoleAttributes Class
#'
#' @field technicalName 
#' @field displayName 
#' @field permissions 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RoleAttributes <- R6::R6Class(
  'RoleAttributes',
  public = list(
    `technicalName` = NULL,
    `displayName` = NULL,
    `permissions` = NULL,
    initialize = function(`technicalName`, `displayName`, `permissions`){
      if (!missing(`technicalName`)) {
        stopifnot(is.character(`technicalName`), length(`technicalName`) == 1)
        self$`technicalName` <- `technicalName`
      }
      if (!missing(`displayName`)) {
        stopifnot(is.character(`displayName`), length(`displayName`) == 1)
        self$`displayName` <- `displayName`
      }
      if (!missing(`permissions`)) {
        stopifnot(is.list(`permissions`), length(`permissions`) != 0)
        lapply(`permissions`, function(x) stopifnot(is.character(x)))
        self$`permissions` <- `permissions`
      }
    },
    toJSON = function() {
      RoleAttributesObject <- list()
      if (!is.null(self$`technicalName`)) {
        RoleAttributesObject[['technicalName']] <- self$`technicalName`
      }
      if (!is.null(self$`displayName`)) {
        RoleAttributesObject[['displayName']] <- self$`displayName`
      }
      if (!is.null(self$`permissions`)) {
        RoleAttributesObject[['permissions']] <- self$`permissions`
      }

      RoleAttributesObject
    },
    fromJSON = function(RoleAttributesJson) {
      RoleAttributesObject <- jsonlite::fromJSON(RoleAttributesJson)
      if (!is.null(RoleAttributesObject$`technicalName`)) {
        self$`technicalName` <- RoleAttributesObject$`technicalName`
      }
      if (!is.null(RoleAttributesObject$`displayName`)) {
        self$`displayName` <- RoleAttributesObject$`displayName`
      }
      if (!is.null(RoleAttributesObject$`permissions`)) {
        self$`permissions` <- RoleAttributesObject$`permissions`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "technicalName": %s,
           "displayName": %s,
           "permissions": [%s]
        }',
        self$`technicalName`,
        self$`displayName`,
        lapply(self$`permissions`, function(x) paste(paste0('"', x, '"'), sep=","))
      )
    },
    fromJSONString = function(RoleAttributesJson) {
      RoleAttributesObject <- jsonlite::fromJSON(RoleAttributesJson)
      self$`technicalName` <- RoleAttributesObject$`technicalName`
      self$`displayName` <- RoleAttributesObject$`displayName`
      self$`permissions` <- RoleAttributesObject$`permissions`
    }
  )
)
