# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' RoleRelationshipData Class
#'
#' @field type 
#' @field id 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RoleRelationshipData <- R6::R6Class(
  'RoleRelationshipData',
  public = list(
    `type` = NULL,
    `id` = NULL,
    initialize = function(`type`, `id`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      RoleRelationshipDataObject <- list()
      if (!is.null(self$`type`)) {
        RoleRelationshipDataObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        RoleRelationshipDataObject[['id']] <- self$`id`
      }

      RoleRelationshipDataObject
    },
    fromJSON = function(RoleRelationshipDataJson) {
      RoleRelationshipDataObject <- jsonlite::fromJSON(RoleRelationshipDataJson)
      if (!is.null(RoleRelationshipDataObject$`type`)) {
        self$`type` <- RoleRelationshipDataObject$`type`
      }
      if (!is.null(RoleRelationshipDataObject$`id`)) {
        self$`id` <- RoleRelationshipDataObject$`id`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s
        }',
        self$`type`,
        self$`id`
      )
    },
    fromJSONString = function(RoleRelationshipDataJson) {
      RoleRelationshipDataObject <- jsonlite::fromJSON(RoleRelationshipDataJson)
      self$`type` <- RoleRelationshipDataObject$`type`
      self$`id` <- RoleRelationshipDataObject$`id`
    }
  )
)
