# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserGroup Class
#'
#' @field type 
#' @field id 
#' @field attributes 
#' @field relationships 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserGroup <- R6::R6Class(
  'UserGroup',
  public = list(
    `type` = NULL,
    `id` = NULL,
    `attributes` = NULL,
    `relationships` = NULL,
    initialize = function(`type`, `id`, `attributes`, `relationships`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`attributes`)) {
        stopifnot(R6::is.R6(`attributes`))
        self$`attributes` <- `attributes`
      }
      if (!missing(`relationships`)) {
        stopifnot(R6::is.R6(`relationships`))
        self$`relationships` <- `relationships`
      }
    },
    toJSON = function() {
      UserGroupObject <- list()
      if (!is.null(self$`type`)) {
        UserGroupObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        UserGroupObject[['id']] <- self$`id`
      }
      if (!is.null(self$`attributes`)) {
        UserGroupObject[['attributes']] <- self$`attributes`$toJSON()
      }
      if (!is.null(self$`relationships`)) {
        UserGroupObject[['relationships']] <- self$`relationships`$toJSON()
      }

      UserGroupObject
    },
    fromJSON = function(UserGroupJson) {
      UserGroupObject <- jsonlite::fromJSON(UserGroupJson)
      if (!is.null(UserGroupObject$`type`)) {
        self$`type` <- UserGroupObject$`type`
      }
      if (!is.null(UserGroupObject$`id`)) {
        self$`id` <- UserGroupObject$`id`
      }
      if (!is.null(UserGroupObject$`attributes`)) {
        attributesObject <- UserGroupAttributes$new()
        attributesObject$fromJSON(jsonlite::toJSON(UserGroupObject$attributes, auto_unbox = TRUE))
        self$`attributes` <- attributesObject
      }
      if (!is.null(UserGroupObject$`relationships`)) {
        relationshipsObject <- UserGroupRelationships$new()
        relationshipsObject$fromJSON(jsonlite::toJSON(UserGroupObject$relationships, auto_unbox = TRUE))
        self$`relationships` <- relationshipsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s,
           "attributes": %s,
           "relationships": %s
        }',
        self$`type`,
        self$`id`,
        self$`attributes`$toJSON(),
        self$`relationships`$toJSON()
      )
    },
    fromJSONString = function(UserGroupJson) {
      UserGroupObject <- jsonlite::fromJSON(UserGroupJson)
      self$`type` <- UserGroupObject$`type`
      self$`id` <- UserGroupObject$`id`
      UserGroupAttributesObject <- UserGroupAttributes$new()
      self$`attributes` <- UserGroupAttributesObject$fromJSON(jsonlite::toJSON(UserGroupObject$attributes, auto_unbox = TRUE))
      UserGroupRelationshipsObject <- UserGroupRelationships$new()
      self$`relationships` <- UserGroupRelationshipsObject$fromJSON(jsonlite::toJSON(UserGroupObject$relationships, auto_unbox = TRUE))
    }
  )
)
