# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserGroupResponseAttribute Class
#'
#' @field name 
#' @field description 
#' @field isMachineEnabled 
#' @field isSystemDefined 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserGroupResponseAttribute <- R6::R6Class(
  'UserGroupResponseAttribute',
  public = list(
    `name` = NULL,
    `description` = NULL,
    `isMachineEnabled` = NULL,
    `isSystemDefined` = NULL,
    initialize = function(`name`, `description`, `isMachineEnabled`, `isSystemDefined`){
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!missing(`isMachineEnabled`)) {
        self$`isMachineEnabled` <- `isMachineEnabled`
      }
      if (!missing(`isSystemDefined`)) {
        self$`isSystemDefined` <- `isSystemDefined`
      }
    },
    toJSON = function() {
      UserGroupResponseAttributeObject <- list()
      if (!is.null(self$`name`)) {
        UserGroupResponseAttributeObject[['name']] <- self$`name`
      }
      if (!is.null(self$`description`)) {
        UserGroupResponseAttributeObject[['description']] <- self$`description`
      }
      if (!is.null(self$`isMachineEnabled`)) {
        UserGroupResponseAttributeObject[['isMachineEnabled']] <- self$`isMachineEnabled`
      }
      if (!is.null(self$`isSystemDefined`)) {
        UserGroupResponseAttributeObject[['isSystemDefined']] <- self$`isSystemDefined`
      }

      UserGroupResponseAttributeObject
    },
    fromJSON = function(UserGroupResponseAttributeJson) {
      UserGroupResponseAttributeObject <- jsonlite::fromJSON(UserGroupResponseAttributeJson)
      if (!is.null(UserGroupResponseAttributeObject$`name`)) {
        self$`name` <- UserGroupResponseAttributeObject$`name`
      }
      if (!is.null(UserGroupResponseAttributeObject$`description`)) {
        self$`description` <- UserGroupResponseAttributeObject$`description`
      }
      if (!is.null(UserGroupResponseAttributeObject$`isMachineEnabled`)) {
        self$`isMachineEnabled` <- UserGroupResponseAttributeObject$`isMachineEnabled`
      }
      if (!is.null(UserGroupResponseAttributeObject$`isSystemDefined`)) {
        self$`isSystemDefined` <- UserGroupResponseAttributeObject$`isSystemDefined`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "name": %s,
           "description": %s,
           "isMachineEnabled": %s,
           "isSystemDefined": %s
        }',
        self$`name`,
        self$`description`,
        self$`isMachineEnabled`,
        self$`isSystemDefined`
      )
    },
    fromJSONString = function(UserGroupResponseAttributeJson) {
      UserGroupResponseAttributeObject <- jsonlite::fromJSON(UserGroupResponseAttributeJson)
      self$`name` <- UserGroupResponseAttributeObject$`name`
      self$`description` <- UserGroupResponseAttributeObject$`description`
      self$`isMachineEnabled` <- UserGroupResponseAttributeObject$`isMachineEnabled`
      self$`isSystemDefined` <- UserGroupResponseAttributeObject$`isSystemDefined`
    }
  )
)
