# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserGroupListLinks Class
#'
#' @field self 
#' @field next 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserGroupListLinks <- R6::R6Class(
  'UserGroupListLinks',
  public = list(
    `self` = NULL,
    `next` = NULL,
    initialize = function(`self`, `next`){
      if (!missing(`self`)) {
        stopifnot(is.character(`self`), length(`self`) == 1)
        self$`self` <- `self`
      }
      if (!missing(`next`)) {
        stopifnot(is.character(`next`), length(`next`) == 1)
        self$`next` <- `next`
      }
    },
    toJSON = function() {
      UserGroupListLinksObject <- list()
      if (!is.null(self$`self`)) {
        UserGroupListLinksObject[['self']] <- self$`self`
      }
      if (!is.null(self$`next`)) {
        UserGroupListLinksObject[['next']] <- self$`next`
      }

      UserGroupListLinksObject
    },
    fromJSON = function(UserGroupListLinksJson) {
      UserGroupListLinksObject <- jsonlite::fromJSON(UserGroupListLinksJson)
      if (!is.null(UserGroupListLinksObject$`self`)) {
        self$`self` <- UserGroupListLinksObject$`self`
      }
      if (!is.null(UserGroupListLinksObject$`next`)) {
        self$`next` <- UserGroupListLinksObject$`next`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "self": %s,
           "next": %s
        }',
        self$`self`,
        self$`next`
      )
    },
    fromJSONString = function(UserGroupListLinksJson) {
      UserGroupListLinksObject <- jsonlite::fromJSON(UserGroupListLinksJson)
      self$`self` <- UserGroupListLinksObject$`self`
      self$`next` <- UserGroupListLinksObject$`next`
    }
  )
)
