# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserRelationships Class
#'
#' @field belongsTo 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserRelationships <- R6::R6Class(
  'UserRelationships',
  public = list(
    `belongsTo` = NULL,
    initialize = function(`belongsTo`){
      if (!missing(`belongsTo`)) {
        stopifnot(R6::is.R6(`belongsTo`))
        self$`belongsTo` <- `belongsTo`
      }
    },
    toJSON = function() {
      UserRelationshipsObject <- list()
      if (!is.null(self$`belongsTo`)) {
        UserRelationshipsObject[['belongsTo']] <- self$`belongsTo`$toJSON()
      }

      UserRelationshipsObject
    },
    fromJSON = function(UserRelationshipsJson) {
      UserRelationshipsObject <- jsonlite::fromJSON(UserRelationshipsJson)
      if (!is.null(UserRelationshipsObject$`belongsTo`)) {
        belongsToObject <- UserGroupRelationship$new()
        belongsToObject$fromJSON(jsonlite::toJSON(UserRelationshipsObject$belongsTo, auto_unbox = TRUE))
        self$`belongsTo` <- belongsToObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "belongsTo": %s
        }',
        self$`belongsTo`$toJSON()
      )
    },
    fromJSONString = function(UserRelationshipsJson) {
      UserRelationshipsObject <- jsonlite::fromJSON(UserRelationshipsJson)
      UserGroupRelationshipObject <- UserGroupRelationship$new()
      self$`belongsTo` <- UserGroupRelationshipObject$fromJSON(jsonlite::toJSON(UserRelationshipsObject$belongsTo, auto_unbox = TRUE))
    }
  )
)
