# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserResponseAttributes Class
#'
#' @field identity 
#' @field profile 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserResponseAttributes <- R6::R6Class(
  'UserResponseAttributes',
  public = list(
    `identity` = NULL,
    `profile` = NULL,
    initialize = function(`identity`, `profile`){
      if (!missing(`identity`)) {
        stopifnot(R6::is.R6(`identity`))
        self$`identity` <- `identity`
      }
      if (!missing(`profile`)) {
        stopifnot(R6::is.R6(`profile`))
        self$`profile` <- `profile`
      }
    },
    toJSON = function() {
      UserResponseAttributesObject <- list()
      if (!is.null(self$`identity`)) {
        UserResponseAttributesObject[['identity']] <- self$`identity`$toJSON()
      }
      if (!is.null(self$`profile`)) {
        UserResponseAttributesObject[['profile']] <- self$`profile`$toJSON()
      }

      UserResponseAttributesObject
    },
    fromJSON = function(UserResponseAttributesJson) {
      UserResponseAttributesObject <- jsonlite::fromJSON(UserResponseAttributesJson)
      if (!is.null(UserResponseAttributesObject$`identity`)) {
        identityObject <- UserResponseAttributesIdentity$new()
        identityObject$fromJSON(jsonlite::toJSON(UserResponseAttributesObject$identity, auto_unbox = TRUE))
        self$`identity` <- identityObject
      }
      if (!is.null(UserResponseAttributesObject$`profile`)) {
        profileObject <- UserResponseAttributesProfile$new()
        profileObject$fromJSON(jsonlite::toJSON(UserResponseAttributesObject$profile, auto_unbox = TRUE))
        self$`profile` <- profileObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "identity": %s,
           "profile": %s
        }',
        self$`identity`$toJSON(),
        self$`profile`$toJSON()
      )
    },
    fromJSONString = function(UserResponseAttributesJson) {
      UserResponseAttributesObject <- jsonlite::fromJSON(UserResponseAttributesJson)
      UserResponseAttributesIdentityObject <- UserResponseAttributesIdentity$new()
      self$`identity` <- UserResponseAttributesIdentityObject$fromJSON(jsonlite::toJSON(UserResponseAttributesObject$identity, auto_unbox = TRUE))
      UserResponseAttributesProfileObject <- UserResponseAttributesProfile$new()
      self$`profile` <- UserResponseAttributesProfileObject$fromJSON(jsonlite::toJSON(UserResponseAttributesObject$profile, auto_unbox = TRUE))
    }
  )
)
