# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserGroupRelationships Class
#'
#' @field hasAccessTo 
#' @field authorizedAs 
#' @field ownedBy 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserGroupRelationships <- R6::R6Class(
  'UserGroupRelationships',
  public = list(
    `hasAccessTo` = NULL,
    `authorizedAs` = NULL,
    `ownedBy` = NULL,
    initialize = function(`hasAccessTo`, `authorizedAs`, `ownedBy`){
      if (!missing(`hasAccessTo`)) {
        stopifnot(R6::is.R6(`hasAccessTo`))
        self$`hasAccessTo` <- `hasAccessTo`
      }
      if (!missing(`authorizedAs`)) {
        stopifnot(R6::is.R6(`authorizedAs`))
        self$`authorizedAs` <- `authorizedAs`
      }
      if (!missing(`ownedBy`)) {
        stopifnot(R6::is.R6(`ownedBy`))
        self$`ownedBy` <- `ownedBy`
      }
    },
    toJSON = function() {
      UserGroupRelationshipsObject <- list()
      if (!is.null(self$`hasAccessTo`)) {
        UserGroupRelationshipsObject[['hasAccessTo']] <- self$`hasAccessTo`$toJSON()
      }
      if (!is.null(self$`authorizedAs`)) {
        UserGroupRelationshipsObject[['authorizedAs']] <- self$`authorizedAs`$toJSON()
      }
      if (!is.null(self$`ownedBy`)) {
        UserGroupRelationshipsObject[['ownedBy']] <- self$`ownedBy`$toJSON()
      }

      UserGroupRelationshipsObject
    },
    fromJSON = function(UserGroupRelationshipsJson) {
      UserGroupRelationshipsObject <- jsonlite::fromJSON(UserGroupRelationshipsJson)
      if (!is.null(UserGroupRelationshipsObject$`hasAccessTo`)) {
        hasAccessToObject <- PartitionRelationship$new()
        hasAccessToObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$hasAccessTo, auto_unbox = TRUE))
        self$`hasAccessTo` <- hasAccessToObject
      }
      if (!is.null(UserGroupRelationshipsObject$`authorizedAs`)) {
        authorizedAsObject <- RoleRelationship$new()
        authorizedAsObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$authorizedAs, auto_unbox = TRUE))
        self$`authorizedAs` <- authorizedAsObject
      }
      if (!is.null(UserGroupRelationshipsObject$`ownedBy`)) {
        ownedByObject <- CustomerRelationship$new()
        ownedByObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$ownedBy, auto_unbox = TRUE))
        self$`ownedBy` <- ownedByObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "hasAccessTo": %s,
           "authorizedAs": %s,
           "ownedBy": %s
        }',
        self$`hasAccessTo`$toJSON(),
        self$`authorizedAs`$toJSON(),
        self$`ownedBy`$toJSON()
      )
    },
    fromJSONString = function(UserGroupRelationshipsJson) {
      UserGroupRelationshipsObject <- jsonlite::fromJSON(UserGroupRelationshipsJson)
      PartitionRelationshipObject <- PartitionRelationship$new()
      self$`hasAccessTo` <- PartitionRelationshipObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$hasAccessTo, auto_unbox = TRUE))
      RoleRelationshipObject <- RoleRelationship$new()
      self$`authorizedAs` <- RoleRelationshipObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$authorizedAs, auto_unbox = TRUE))
      CustomerRelationshipObject <- CustomerRelationship$new()
      self$`ownedBy` <- CustomerRelationshipObject$fromJSON(jsonlite::toJSON(UserGroupRelationshipsObject$ownedBy, auto_unbox = TRUE))
    }
  )
)
