# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' User Class
#'
#' @field type 
#' @field id 
#' @field attributes 
#' @field relationships 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
User <- R6::R6Class(
  'User',
  public = list(
    `type` = NULL,
    `id` = NULL,
    `attributes` = NULL,
    `relationships` = NULL,
    initialize = function(`type`, `id`, `attributes`, `relationships`){
      if (!missing(`type`)) {
        stopifnot(is.character(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`attributes`)) {
        stopifnot(R6::is.R6(`attributes`))
        self$`attributes` <- `attributes`
      }
      if (!missing(`relationships`)) {
        stopifnot(R6::is.R6(`relationships`))
        self$`relationships` <- `relationships`
      }
    },
    toJSON = function() {
      UserObject <- list()
      if (!is.null(self$`type`)) {
        UserObject[['type']] <- self$`type`
      }
      if (!is.null(self$`id`)) {
        UserObject[['id']] <- self$`id`
      }
      if (!is.null(self$`attributes`)) {
        UserObject[['attributes']] <- self$`attributes`$toJSON()
      }
      if (!is.null(self$`relationships`)) {
        UserObject[['relationships']] <- self$`relationships`$toJSON()
      }

      UserObject
    },
    fromJSON = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      if (!is.null(UserObject$`type`)) {
        self$`type` <- UserObject$`type`
      }
      if (!is.null(UserObject$`id`)) {
        self$`id` <- UserObject$`id`
      }
      if (!is.null(UserObject$`attributes`)) {
        attributesObject <- UserResponseAttributes$new()
        attributesObject$fromJSON(jsonlite::toJSON(UserObject$attributes, auto_unbox = TRUE))
        self$`attributes` <- attributesObject
      }
      if (!is.null(UserObject$`relationships`)) {
        relationshipsObject <- UserRelationships$new()
        relationshipsObject$fromJSON(jsonlite::toJSON(UserObject$relationships, auto_unbox = TRUE))
        self$`relationships` <- relationshipsObject
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "type": %s,
           "id": %s,
           "attributes": %s,
           "relationships": %s
        }',
        self$`type`,
        self$`id`,
        self$`attributes`$toJSON(),
        self$`relationships`$toJSON()
      )
    },
    fromJSONString = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      self$`type` <- UserObject$`type`
      self$`id` <- UserObject$`id`
      UserResponseAttributesObject <- UserResponseAttributes$new()
      self$`attributes` <- UserResponseAttributesObject$fromJSON(jsonlite::toJSON(UserObject$attributes, auto_unbox = TRUE))
      UserRelationshipsObject <- UserRelationships$new()
      self$`relationships` <- UserRelationshipsObject$fromJSON(jsonlite::toJSON(UserObject$relationships, auto_unbox = TRUE))
    }
  )
)
