# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserGroupRelationship Class
#'
#' @field data 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserGroupRelationship <- R6::R6Class(
  'UserGroupRelationship',
  public = list(
    `data` = NULL,
    initialize = function(`data`){
      if (!missing(`data`)) {
        stopifnot(is.list(`data`), length(`data`) != 0)
        lapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
    },
    toJSON = function() {
      UserGroupRelationshipObject <- list()
      if (!is.null(self$`data`)) {
        UserGroupRelationshipObject[['data']] <- lapply(self$`data`, function(x) x$toJSON())
      }

      UserGroupRelationshipObject
    },
    fromJSON = function(UserGroupRelationshipJson) {
      UserGroupRelationshipObject <- jsonlite::fromJSON(UserGroupRelationshipJson)
      if (!is.null(UserGroupRelationshipObject$`data`)) {
        self$`data` <- lapply(UserGroupRelationshipObject$`data`, function(x) {
          dataObject <- UserGroupRelationshipData$new()
          dataObject$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE))
          dataObject
        })
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "data": [%s]
        }',
        lapply(self$`data`, function(x) paste(x$toJSON(), sep=","))
      )
    },
    fromJSONString = function(UserGroupRelationshipJson) {
      UserGroupRelationshipObject <- jsonlite::fromJSON(UserGroupRelationshipJson)
      self$`data` <- lapply(UserGroupRelationshipObject$`data`, function(x) UserGroupRelationshipData$new()$fromJSON(jsonlite::toJSON(x, auto_unbox = TRUE)))
    }
  )
)
