# Accounts API
#
# Accounts API 
#
# OpenAPI spec version: 0.9.5
# 
# Generated by: https://github.com/swagger-api/swagger-codegen.git

#' UserResponseAttributesProfile Class
#'
#' @field freeText 
#' @field jobDescription 
#' @field phone 
#' @field profileImage 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserResponseAttributesProfile <- R6::R6Class(
  'UserResponseAttributesProfile',
  public = list(
    `freeText` = NULL,
    `jobDescription` = NULL,
    `phone` = NULL,
    `profileImage` = NULL,
    initialize = function(`freeText`, `jobDescription`, `phone`, `profileImage`){
      if (!missing(`freeText`)) {
        stopifnot(is.character(`freeText`), length(`freeText`) == 1)
        self$`freeText` <- `freeText`
      }
      if (!missing(`jobDescription`)) {
        stopifnot(is.character(`jobDescription`), length(`jobDescription`) == 1)
        self$`jobDescription` <- `jobDescription`
      }
      if (!missing(`phone`)) {
        stopifnot(is.character(`phone`), length(`phone`) == 1)
        self$`phone` <- `phone`
      }
      if (!missing(`profileImage`)) {
        stopifnot(is.character(`profileImage`), length(`profileImage`) == 1)
        self$`profileImage` <- `profileImage`
      }
    },
    toJSON = function() {
      UserResponseAttributesProfileObject <- list()
      if (!is.null(self$`freeText`)) {
        UserResponseAttributesProfileObject[['freeText']] <- self$`freeText`
      }
      if (!is.null(self$`jobDescription`)) {
        UserResponseAttributesProfileObject[['jobDescription']] <- self$`jobDescription`
      }
      if (!is.null(self$`phone`)) {
        UserResponseAttributesProfileObject[['phone']] <- self$`phone`
      }
      if (!is.null(self$`profileImage`)) {
        UserResponseAttributesProfileObject[['profileImage']] <- self$`profileImage`
      }

      UserResponseAttributesProfileObject
    },
    fromJSON = function(UserResponseAttributesProfileJson) {
      UserResponseAttributesProfileObject <- jsonlite::fromJSON(UserResponseAttributesProfileJson)
      if (!is.null(UserResponseAttributesProfileObject$`freeText`)) {
        self$`freeText` <- UserResponseAttributesProfileObject$`freeText`
      }
      if (!is.null(UserResponseAttributesProfileObject$`jobDescription`)) {
        self$`jobDescription` <- UserResponseAttributesProfileObject$`jobDescription`
      }
      if (!is.null(UserResponseAttributesProfileObject$`phone`)) {
        self$`phone` <- UserResponseAttributesProfileObject$`phone`
      }
      if (!is.null(UserResponseAttributesProfileObject$`profileImage`)) {
        self$`profileImage` <- UserResponseAttributesProfileObject$`profileImage`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "freeText": %s,
           "jobDescription": %s,
           "phone": %s,
           "profileImage": %s
        }',
        self$`freeText`,
        self$`jobDescription`,
        self$`phone`,
        self$`profileImage`
      )
    },
    fromJSONString = function(UserResponseAttributesProfileJson) {
      UserResponseAttributesProfileObject <- jsonlite::fromJSON(UserResponseAttributesProfileJson)
      self$`freeText` <- UserResponseAttributesProfileObject$`freeText`
      self$`jobDescription` <- UserResponseAttributesProfileObject$`jobDescription`
      self$`phone` <- UserResponseAttributesProfileObject$`phone`
      self$`profileImage` <- UserResponseAttributesProfileObject$`profileImage`
    }
  )
)
