/* 
 * Accounts API
 *
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MachineUserResponseAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MachineUserResponseAttributesTests
    {
        // TODO uncomment below to declare an instance variable for MachineUserResponseAttributes
        //private MachineUserResponseAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MachineUserResponseAttributes
            //instance = new MachineUserResponseAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MachineUserResponseAttributes
        /// </summary>
        [Test]
        public void MachineUserResponseAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MachineUserResponseAttributes
            //Assert.IsInstanceOfType<MachineUserResponseAttributes> (instance, "variable 'instance' is a MachineUserResponseAttributes");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Test]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'OAuth'
        /// </summary>
        [Test]
        public void OAuthTest()
        {
            // TODO unit test for the property 'OAuth'
        }

    }

}
