/* 
 * Accounts API
 *
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MachineUserOAuth
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MachineUserOAuthTests
    {
        // TODO uncomment below to declare an instance variable for MachineUserOAuth
        //private MachineUserOAuth instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MachineUserOAuth
            //instance = new MachineUserOAuth();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MachineUserOAuth
        /// </summary>
        [Test]
        public void MachineUserOAuthInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MachineUserOAuth
            //Assert.IsInstanceOfType<MachineUserOAuth> (instance, "variable 'instance' is a MachineUserOAuth");
        }


        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Test]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }
        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Test]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }
        /// <summary>
        /// Test the property 'Audience'
        /// </summary>
        [Test]
        public void AudienceTest()
        {
            // TODO unit test for the property 'Audience'
        }
        /// <summary>
        /// Test the property 'SecretCreated'
        /// </summary>
        [Test]
        public void SecretCreatedTest()
        {
            // TODO unit test for the property 'SecretCreated'
        }
        /// <summary>
        /// Test the property 'SecretRotated'
        /// </summary>
        [Test]
        public void SecretRotatedTest()
        {
            // TODO unit test for the property 'SecretRotated'
        }

    }

}
