/* 
 * Accounts API
 *
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserGroupRelationships
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserGroupRelationshipsTests
    {
        // TODO uncomment below to declare an instance variable for UserGroupRelationships
        //private UserGroupRelationships instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserGroupRelationships
            //instance = new UserGroupRelationships();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserGroupRelationships
        /// </summary>
        [Test]
        public void UserGroupRelationshipsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserGroupRelationships
            //Assert.IsInstanceOfType<UserGroupRelationships> (instance, "variable 'instance' is a UserGroupRelationships");
        }


        /// <summary>
        /// Test the property 'HasAccessTo'
        /// </summary>
        [Test]
        public void HasAccessToTest()
        {
            // TODO unit test for the property 'HasAccessTo'
        }
        /// <summary>
        /// Test the property 'AuthorizedAs'
        /// </summary>
        [Test]
        public void AuthorizedAsTest()
        {
            // TODO unit test for the property 'AuthorizedAs'
        }
        /// <summary>
        /// Test the property 'OwnedBy'
        /// </summary>
        [Test]
        public void OwnedByTest()
        {
            // TODO unit test for the property 'OwnedBy'
        }

    }

}
