/* 
 * Accounts API
 *
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing UserGroupAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserGroupAttributesTests
    {
        // TODO uncomment below to declare an instance variable for UserGroupAttributes
        //private UserGroupAttributes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserGroupAttributes
            //instance = new UserGroupAttributes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserGroupAttributes
        /// </summary>
        [Test]
        public void UserGroupAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserGroupAttributes
            //Assert.IsInstanceOfType<UserGroupAttributes> (instance, "variable 'instance' is a UserGroupAttributes");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'IsMachineEnabled'
        /// </summary>
        [Test]
        public void IsMachineEnabledTest()
        {
            // TODO unit test for the property 'IsMachineEnabled'
        }
        /// <summary>
        /// Test the property 'IsSystemDefined'
        /// </summary>
        [Test]
        public void IsSystemDefinedTest()
        {
            // TODO unit test for the property 'IsSystemDefined'
        }

    }

}
