# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PartitionRelationships(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owned_by_customer': 'CustomerRelationship'
    }

    attribute_map = {
        'owned_by_customer': 'ownedByCustomer'
    }

    def __init__(self, owned_by_customer=None):  # noqa: E501
        """PartitionRelationships - a model defined in Swagger"""  # noqa: E501
        self._owned_by_customer = None
        self.discriminator = None
        self.owned_by_customer = owned_by_customer

    @property
    def owned_by_customer(self):
        """Gets the owned_by_customer of this PartitionRelationships.  # noqa: E501


        :return: The owned_by_customer of this PartitionRelationships.  # noqa: E501
        :rtype: CustomerRelationship
        """
        return self._owned_by_customer

    @owned_by_customer.setter
    def owned_by_customer(self, owned_by_customer):
        """Sets the owned_by_customer of this PartitionRelationships.


        :param owned_by_customer: The owned_by_customer of this PartitionRelationships.  # noqa: E501
        :type: CustomerRelationship
        """
        if owned_by_customer is None:
            raise ValueError("Invalid value for `owned_by_customer`, must not be `None`")  # noqa: E501

        self._owned_by_customer = owned_by_customer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PartitionRelationships, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PartitionRelationships):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
