# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RoleAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'technical_name': 'str',
        'display_name': 'str',
        'permissions': 'list[str]'
    }

    attribute_map = {
        'technical_name': 'technicalName',
        'display_name': 'displayName',
        'permissions': 'permissions'
    }

    def __init__(self, technical_name=None, display_name=None, permissions=None):  # noqa: E501
        """RoleAttributes - a model defined in Swagger"""  # noqa: E501
        self._technical_name = None
        self._display_name = None
        self._permissions = None
        self.discriminator = None
        self.technical_name = technical_name
        self.display_name = display_name
        self.permissions = permissions

    @property
    def technical_name(self):
        """Gets the technical_name of this RoleAttributes.  # noqa: E501


        :return: The technical_name of this RoleAttributes.  # noqa: E501
        :rtype: str
        """
        return self._technical_name

    @technical_name.setter
    def technical_name(self, technical_name):
        """Sets the technical_name of this RoleAttributes.


        :param technical_name: The technical_name of this RoleAttributes.  # noqa: E501
        :type: str
        """
        if technical_name is None:
            raise ValueError("Invalid value for `technical_name`, must not be `None`")  # noqa: E501

        self._technical_name = technical_name

    @property
    def display_name(self):
        """Gets the display_name of this RoleAttributes.  # noqa: E501


        :return: The display_name of this RoleAttributes.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this RoleAttributes.


        :param display_name: The display_name of this RoleAttributes.  # noqa: E501
        :type: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name

    @property
    def permissions(self):
        """Gets the permissions of this RoleAttributes.  # noqa: E501


        :return: The permissions of this RoleAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._permissions

    @permissions.setter
    def permissions(self, permissions):
        """Sets the permissions of this RoleAttributes.


        :param permissions: The permissions of this RoleAttributes.  # noqa: E501
        :type: list[str]
        """
        if permissions is None:
            raise ValueError("Invalid value for `permissions`, must not be `None`")  # noqa: E501

        self._permissions = permissions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RoleAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RoleAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
