# coding: utf-8

"""
    Accounts API

    Accounts API   # noqa: E501

    OpenAPI spec version: 0.9.5
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserGroupAttributes(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'is_machine_enabled': 'bool',
        'is_system_defined': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'is_machine_enabled': 'isMachineEnabled',
        'is_system_defined': 'isSystemDefined'
    }

    def __init__(self, name=None, description=None, is_machine_enabled=None, is_system_defined=None):  # noqa: E501
        """UserGroupAttributes - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._is_machine_enabled = None
        self._is_system_defined = None
        self.discriminator = None
        self.name = name
        self.description = description
        if is_machine_enabled is not None:
            self.is_machine_enabled = is_machine_enabled
        if is_system_defined is not None:
            self.is_system_defined = is_system_defined

    @property
    def name(self):
        """Gets the name of this UserGroupAttributes.  # noqa: E501

        Name of the user group   # noqa: E501

        :return: The name of this UserGroupAttributes.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserGroupAttributes.

        Name of the user group   # noqa: E501

        :param name: The name of this UserGroupAttributes.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self):
        """Gets the description of this UserGroupAttributes.  # noqa: E501

        Description of the user group   # noqa: E501

        :return: The description of this UserGroupAttributes.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UserGroupAttributes.

        Description of the user group   # noqa: E501

        :param description: The description of this UserGroupAttributes.  # noqa: E501
        :type: str
        """
        if description is None:
            raise ValueError("Invalid value for `description`, must not be `None`")  # noqa: E501

        self._description = description

    @property
    def is_machine_enabled(self):
        """Gets the is_machine_enabled of this UserGroupAttributes.  # noqa: E501


        :return: The is_machine_enabled of this UserGroupAttributes.  # noqa: E501
        :rtype: bool
        """
        return self._is_machine_enabled

    @is_machine_enabled.setter
    def is_machine_enabled(self, is_machine_enabled):
        """Sets the is_machine_enabled of this UserGroupAttributes.


        :param is_machine_enabled: The is_machine_enabled of this UserGroupAttributes.  # noqa: E501
        :type: bool
        """

        self._is_machine_enabled = is_machine_enabled

    @property
    def is_system_defined(self):
        """Gets the is_system_defined of this UserGroupAttributes.  # noqa: E501


        :return: The is_system_defined of this UserGroupAttributes.  # noqa: E501
        :rtype: bool
        """
        return self._is_system_defined

    @is_system_defined.setter
    def is_system_defined(self, is_system_defined):
        """Sets the is_system_defined of this UserGroupAttributes.


        :param is_system_defined: The is_system_defined of this UserGroupAttributes.  # noqa: E501
        :type: bool
        """

        self._is_system_defined = is_system_defined

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserGroupAttributes, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserGroupAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
