/**
* Accounts API
* Accounts API 
*
* OpenAPI spec version: 0.9.5
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/package io.swagger.server

import io.ktor.application.ApplicationCall
import io.ktor.http.HttpMethod
import io.ktor.locations.handle
import io.ktor.locations.location
import io.ktor.locations.Location
import io.ktor.util.pipeline.PipelineContext
import io.ktor.routing.Route
import io.ktor.routing.method
import io.swagger.server.models.*;


// NOTE: ktor-location@0.9.0 is missing extension for Route.delete. This includes it.
inline fun <reified T : Any> Route.delete(noinline body: suspend PipelineContext<Unit, ApplicationCall>.(T) -> Unit): Route {
    return location(T::class) {
        method(HttpMethod.Delete) {
            handle(body)
        }
    }
}

object Paths {
    /**
     * List Partitions for Customer
     * Get the partitions for the specified customer
     * @param customerId Customer ID 
     * @param include include related resources (optional)
     */
    @Location("/customers/{customerId}/partitions") class getPartitions(val customerId: kotlin.String, val include: kotlin.String)

    /**
     * Get the usergroups of caller
     * Return list of the usergroup (user identity inferred from the SUB in the token)

     * @param page[cursor] Cursor to fetch next paginated items (optional)
     * @param page[size] Max number of items to return in a page (optional, default to 20)
     */
    @Location("/me/usergroups") class getMeUsergroups(val page[cursor]: kotlin.String, val page[size]: kotlin.Int)

}
