/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param self  for example: '''/me/customers'''
 * @param next  for example: '''/me/customers?page[cursor]=qwerty'''
 */
case class CustomerListLinks (
  self: String,
  next: Option[String] = None
)

