/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param `type`  for example: '''Customer'''
 * @param id ID for example: '''209d38aa-02c1-48ab-bf37-2716f1ddfeb6'''
 * @param attributes 
 */
case class PartitionListIncluded (
  `type`: String,
  id: String,
  attributes: PartitionList_attributes
)

