/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param technicalName  for example: '''sbs.user'''
 * @param displayName  for example: '''User'''
 * @param permissions 
 */
case class RoleAttributes (
  technicalName: String,
  displayName: String,
  permissions: List[String]
)

