/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param `type` 
 * @param id  for example: '''38c5b37e-1143-4760-98b9-0bf15fdf2c6f'''
 */
case class RoleRelationshipData (
  `type`: String,
  id: String
)

