/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param `type`  for example: '''UserGroup'''
 * @param id  for example: '''f68a9762-9679-4c17-9012-ec9271f4087f'''
 * @param attributes 
 * @param relationships 
 */
case class UserGroupResponseData (
  `type`: String,
  id: String,
  attributes: UserGroupResponseAttribute,
  relationships: Option[UserGroup_relationships] = None
)

