/**
 * Accounts API
 * Accounts API 
 *
 * OpenAPI spec version: 0.9.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * @param freeText free text user info
 * @param jobDescription user's job description for example: '''Engineer'''
 * @param phone user's contact phone number for example: '''222-333-5674'''
 * @param profileImage user's profile image
 */
case class UserResponseAttributesProfile (
  freeText: Option[String] = None,
  jobDescription: Option[String] = None,
  phone: Option[String] = None,
  profileImage: Option[String] = None
)

