name: Swagger Codegen

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Swagger Codegen
      run: |
        wget https://repo1.maven.org/maven2/io/swagger/codegen/v3/swagger-codegen-cli/3.0.27/swagger-codegen-cli-3.0.27.jar -O swagger-codegen-cli.jar
        chmod +x swagger-codegen-cli.jar

    - name: Generate SDKs
      run: |
        languages=("python" "java" "javascript" "ruby" "php" "csharp" "swift5" "go" "kotlin-client" "kotlin-server" "scala" "typescript-fetch" "typescript-angular" "dart" "r")
        
        for lang in "${languages[@]}"
        do
          echo "Generating $lang SDK..."
          java -jar swagger-codegen-cli.jar generate -i  -l $lang -o output/$lang
        done

    - name: Commit and Push Changes
      run: |
        echo {{ secrets.MY_GITHUB_TOKEN }}
        git config --local user.email "jigar.pj@somaiya.edu"
        git config --local user.name "Jigar Joshi"
        git add .
        git commit -m "Generate SDKs"
        git push
      env:
        GH_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
