//
// CustomerAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerAttributes: Codable {

    public var name: String
    public var customerMembershipState: UserMembershipAttributes?

    public init(name: String, customerMembershipState: UserMembershipAttributes? = nil) {
        self.name = name
        self.customerMembershipState = customerMembershipState
    }


}
