//
// CustomerMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerMeta: Codable {

    public var updatedAt: Date?
    public var updatedBy: String?

    public init(updatedAt: Date? = nil, updatedBy: String? = nil) {
        self.updatedAt = updatedAt
        self.updatedBy = updatedBy
    }


}
