//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Customer: Codable {

    public enum ModelType: String, Codable { 
        case customer = "Customer"
    }
    public var type: ModelType
    public var _id: String
    public var attributes: CustomerAttributes
    public var meta: CustomerMeta?

    public init(type: ModelType, _id: String, attributes: CustomerAttributes, meta: CustomerMeta? = nil) {
        self.type = type
        self._id = _id
        self.attributes = attributes
        self.meta = meta
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case attributes
        case meta
    }

}
