//
// CustomerRelationship.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomerRelationship: Codable {

    public var data: CustomerRelationshipData

    public init(data: CustomerRelationshipData) {
        self.data = data
    }


}
