//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var data: PartitionList?

    public init(data: PartitionList? = nil) {
        self.data = data
    }


}
