//
// MachineUserRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MachineUserRelationships: Codable {

    public var ownedBy: CustomerRelationship?

    public init(ownedBy: CustomerRelationship? = nil) {
        self.ownedBy = ownedBy
    }


}
