//
// PartitionRelationship.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PartitionRelationship: Codable {

    public var data: [PartitionRelationshipData]

    public init(data: [PartitionRelationshipData]) {
        self.data = data
    }


}
