//
// Partition.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Partition: Codable {

    public var type: String
    public var _id: String
    public var attributes: PartitionAttributes
    public var relationships: PartitionRelationships?

    public init(type: String, _id: String, attributes: PartitionAttributes, relationships: PartitionRelationships? = nil) {
        self.type = type
        self._id = _id
        self.attributes = attributes
        self.relationships = relationships
    }

    public enum CodingKeys: String, CodingKey { 
        case type
        case _id = "id"
        case attributes
        case relationships
    }

}
