//
// UserResponseAttributesProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserResponseAttributesProfile: Codable {

    /** free text user info */
    public var freeText: String?
    /** user&#x27;s job description */
    public var jobDescription: String?
    /** user&#x27;s contact phone number */
    public var phone: String?
    /** user&#x27;s profile image */
    public var profileImage: String?

    public init(freeText: String? = nil, jobDescription: String? = nil, phone: String? = nil, profileImage: String? = nil) {
        self.freeText = freeText
        self.jobDescription = jobDescription
        self.phone = phone
        self.profileImage = profileImage
    }


}
