//
// UserGroupAttributes.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserGroupAttributes: Codable {

    /** Name of the user group  */
    public var name: String
    /** Description of the user group  */
    public var _description: String
    public var isMachineEnabled: Bool?
    public var isSystemDefined: Bool?

    public init(name: String, _description: String, isMachineEnabled: Bool? = nil, isSystemDefined: Bool? = nil) {
        self.name = name
        self._description = _description
        self.isMachineEnabled = isMachineEnabled
        self.isSystemDefined = isSystemDefined
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case _description = "description"
        case isMachineEnabled
        case isSystemDefined
    }

}
