//
// UserResponseAttributesIdentity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** user identity details */

public struct UserResponseAttributesIdentity: Codable {

    /** email address of the user */
    public var emailId: String
    /** horizon ID of the user within Siemens ID */
    public var externalId: String
    /** user&#x27;s family name */
    public var familyName: String?
    /** user&#x27;s full name */
    public var fullName: String?
    /** user&#x27;s given name */
    public var givenName: String

    public init(emailId: String, externalId: String, familyName: String? = nil, fullName: String? = nil, givenName: String) {
        self.emailId = emailId
        self.externalId = externalId
        self.familyName = familyName
        self.fullName = fullName
        self.givenName = givenName
    }


}
