//
// UserRelationships.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserRelationships: Codable {

    public var belongsTo: UserGroupRelationship?

    public init(belongsTo: UserGroupRelationship? = nil) {
        self.belongsTo = belongsTo
    }


}
